# Generated by Django 3.2.4 on 2023-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_branchnewsletter_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter_picture/'),
        ),
    ]
