# Generated by Django 3.2.4 on 2023-09-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_branch_integration'),
        ('newsletter', '0003_newsletter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.company'),
        ),
    ]
