# Generated by Django 3.2.4 on 2023-06-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('customer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='customer_request.customerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='feedback.rating')),
            ],
        ),
    ]
