# Generated by Django 3.2.4 on 2023-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_branch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Активен'), (2, 'Не активен'), (3, 'Ожидается оплата')], default=2),
        ),
    ]
