# Generated by Django 3.2.4 on 2023-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Тариф'), (2, 'Стандарт'), (3, 'ВИП')], default=1),
        ),
    ]
