# Generated by Django 3.2.4 on 2023-09-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Владелец'), (2, 'Админ'), (3, 'Работник')], default=3),
        ),
    ]
