# Generated by Django 3.2.4 on 2023-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('cards_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ManyToManyField(to='accounts.Company')),
                ('shop', models.ManyToManyField(to='shop.Shop')),
            ],
        ),
    ]
