# Generated by Django 3.2.4 on 2023-08-28 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
