# Generated by Django 3.2.4 on 2023-08-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_request', '0002_alter_customerrequest_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
