# Generated by Django 3.2.4 on 2023-09-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='branch',
        ),
    ]
