# Generated by Django 3.2.4 on 2023-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_integration_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
