# Generated by Django 3.2.4 on 2023-08-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_branch_address'),
        ('raffle_prizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleprize',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.company'),
            preserve_default=False,
        ),
    ]
