# Generated by Django 3.2.4 on 2023-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_prizes', '0002_raffleprize_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleprize',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raffleprize',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
