# Generated by Django 3.2.4 on 2023-08-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_created_at'),
        ('raffle_prizes', '0004_auto_20230823_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='customer_request',
        ),
        migrations.AddField(
            model_name='promocode',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
