# Generated by Django 3.2.4 on 2023-08-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_created_at'),
        ('raffle_prizes', '0005_auto_20230823_2227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('raffle_prize', 'customer')},
        ),
    ]
