# Generated by Django 3.2.4 on 2023-09-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_prizes', '0007_raffleprize_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='raffle_prize',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffle_prizes.raffleprize'),
        ),
    ]
