# Generated by Django 3.2.4 on 2023-09-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_prizes', '0009_auto_20230906_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='customer',
        ),
        migrations.CreateModel(
            name='CheckingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=180, unique=True)),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='raffle_prizes.winner')),
            ],
        ),
    ]
